export type HotSource = {
  id: string;
  label: string;
  tip: string;
};

// 来源清单同步自 ../next-daily-hot/src/enums/index.tsx 的 HOT_ITEMS（value/label/tip）。
export const HOT_SOURCES: HotSource[] = [
  { id: "weibo", label: "微博", tip: "热搜榜" },
  { id: "xiaohongshu", label: "小红书", tip: "实时热榜" },
  { id: "bilibili", label: "哔哩哔哩", tip: "热门榜" },
  { id: "douyin", label: "抖音", tip: "热点榜" },
  { id: "toutiao", label: "今日头条", tip: "热榜" },
  { id: "zhihu", label: "知乎", tip: "热榜" },
  { id: "baidu", label: "百度", tip: "热搜榜" },
  { id: "baidu-realtime", label: "百度", tip: "实时热搜" },
  { id: "baidu-movie", label: "百度", tip: "电影榜" },
  { id: "baidu-teleplay", label: "百度", tip: "电视剧榜" },
  { id: "baidu-novel", label: "百度", tip: "小说榜" },
  { id: "baidu-car", label: "百度", tip: "汽车榜" },
  { id: "baidu-game", label: "百度", tip: "游戏榜" },
  { id: "baidutieba", label: "百度贴吧", tip: "热议榜" },
  { id: "qq", label: "腾讯新闻", tip: "热点榜" },
  { id: "hupu", label: "虎扑", tip: "步行街热帖" },
  { id: "juejin", label: "稀土掘金", tip: "热榜" },
  { id: "github-trending", label: "Github", tip: "热门仓库" },
  { id: "hello-github", label: "HelloGithub", tip: "精选" },
  { id: "csdn", label: "CSDN", tip: "热榜" },
  { id: "netease", label: "网易新闻", tip: "热榜" },
  { id: "quark", label: "夸克", tip: "今日热点" },
  { id: "lol", label: "英雄联盟", tip: "更新公告" },
  { id: "thepaper", label: "澎湃新闻", tip: "热榜" },
  { id: "kuaishou", label: "快手", tip: "热榜" },
  { id: "dongchedi", label: "懂车帝", tip: "热搜榜" },
  { id: "history-today", label: "百度百科", tip: "历史上的今天" },
  { id: "weread", label: "微信读书", tip: "飙升榜" },
  { id: "douban-movic", label: "豆瓣电影", tip: "新片榜" },
  { id: "netease-music", label: "网易云音乐", tip: "热歌榜" },
  { id: "woshipm", label: "人人都是产品经理", tip: "热榜" },
  { id: "36kr", label: "36氪", tip: "24小时热榜" },
  { id: "huxiu", label: "虎嗅", tip: "最新资讯" },
  { id: "zhihu-daily", label: "知乎日报", tip: "推荐榜" },
  { id: "ifanr", label: "爱范儿", tip: "快讯" },
  { id: "ithome", label: "IT之家", tip: "热榜" },
  { id: "51cto", label: "51CTO", tip: "推荐榜" },
  { id: "52pojie", label: "吾爱破解", tip: "榜单" },
  { id: "acfun", label: "AcFun", tip: "排行榜" },
  { id: "coolapk", label: "酷安", tip: "热榜" },
  { id: "dgtle", label: "数字尾巴", tip: "热门" },
  { id: "douban-group", label: "豆瓣讨论小组", tip: "讨论精选" },
  { id: "earthquake", label: "中国地震台", tip: "地震速报" },
  { id: "gameres", label: "游戏研究", tip: "热门" },
  { id: "geekpark", label: "极客公园", tip: "热榜" },
  { id: "genshin", label: "原神", tip: "最新消息" },
  { id: "guokr", label: "果壳", tip: "热门文章" },
  { id: "hackernews", label: "Hacker News", tip: "热门" },
  { id: "honkai", label: "崩坏3", tip: "最新动态" },
  { id: "hostloc", label: "全球主机交流", tip: "榜单" },
  { id: "ithome-xijiayi", label: "IT之家", tip: "喜加一" },
  { id: "jianshu", label: "简书", tip: "热门推荐" },
  { id: "linuxdo", label: "LinuxDo", tip: "热门" },
  { id: "miyoushe", label: "米游社", tip: "最新消息" },
  { id: "netease-news", label: "网易新闻", tip: "热点榜" },
  { id: "newsmth", label: "水木社区", tip: "热门" },
  { id: "ngabbs", label: "NGA", tip: "热帖" },
  { id: "nodeseek", label: "NodeSeek", tip: "最新动态" },
  { id: "nytimes", label: "纽约时报", tip: "新闻" },
  { id: "producthunt", label: "Product Hunt", tip: "热门" },
  { id: "qq-news", label: "腾讯新闻", tip: "热点榜" },
  { id: "sina-news", label: "新浪新闻", tip: "热点榜" },
  { id: "sina", label: "新浪网", tip: "热榜" },
  { id: "smzdm", label: "什么值得买", tip: "热门" },
  { id: "sspai", label: "少数派", tip: "热榜" },
  { id: "starrail", label: "崩坏：星穹铁道", tip: "最新动态" },
  { id: "v2ex", label: "V2EX", tip: "主题榜" },
  { id: "weatheralarm", label: "中央气象台", tip: "全国气象预警" },
  { id: "yystv", label: "YYSTV", tip: "热门" }
];
